### ISSUE TITLE
Issue or maybe not?

### ISSUE THREAD

**Issue by Digileksik1** [mijora/omniva-opencart#2]
Labas,
visaip nesėkmingai bandau įdiegti šį modulį į savo opencart 3.0.3.8 puslapį. Per OC automatinį diegimą nesigauna niekaip net ir pakėlus paketo dydžio ribą. O keliant rankiniu būdų per ftp vis gaunu klaidą.

[Fri Oct 28 14:53:33.152440 2022] [lsapi:error] [pid 12852:tid 140142064776960] [client 80.243.29.139:60714] [host www.*****.lt] Backend fatal error: PHP Fatal error:  Uncaught Error: Class 'Mijora\\OmnivaOpencart\\Helper' not found in /home/aus4041/domains/*****/public_html/admin/controller/extension/shipping/omniva_m.php:83\nStack trace:\n#0 /home/aus4041/domains/*****/public_html/system/storageyojleaew3wky/modification/system/engine/action.php(79): ControllerExtensionShippingOmnivaM->uninstall(Array)\n#1 /home/aus4041/domains/*****/public_html/system/storageyojleaew3wky/modification/system/engine/loader.php(48): Action->execute(Object(Registry), Array)\n#2 /home/aus4041/domains/*****/public_html/admin/controller/extension/extension/shipping.php(44): Loader->controller('extension/shipp...')\n#3 /home/aus4041/domains/*****/public_html/system/storageyojleaew3wky/modification/system/engine/action.php(79): ControllerExtensionExtensionShipping->uninstall()\n#4 /home/aus4041/domains/*****/public_html/admin/controller/startup/router.php(26): Action->execute(Object(Registry), Array)\n#5 /home/aus4041/domains/*****/public_html/system/storageyojleaew3wky/m in /home/aus4041/domains/*****/public_html/admin/controller/extension/shipping/omniva_m.php on line 83\n, referer: http://www.*****.lt/admin/index.php?route=marketplace/extension&user_token=7lAjBW79yU1sjCkiOdYU510rJMFazOhy

Neleidžia nei įdiegti nei išdiegti ir meta šias klaidas. Ką darau blogai, galbūt serverio nustatymai blogi ? Bandžiau viską daryti švariai:
ištrintos visos duomenų bazės, ištrintas ftp aplankas suinstaliuota naujai opencart programa įdiegtas integruotas vqmod modulis ir tada bandoma įrašyti omniva modulį ir štai problema.

**Comment by LithMage** [comment]
Sveiki,

vqmod moduliui nereikalingas, patikrinkite jog zip failas yra su galu ocmod.zip ir tuomet pakėlus leidžiamo upload dydį turėtų užkelti per standartinį opencart instalerį. Rankiniu būdų užkėlus gali būti jog vartotojo su kuriuo keliate failų negali naudoti serverio vartotojas (įprastai www-data). Tai užkėlus rankiniu būdu pamėginkite rekursyviai sutvarkyti kam priklauso failai.

**Comment by LithMage** [comment]
Closing as resolved.
