### ISSUE TITLE
bug with Opencart 3.0.3.8 + Journal 3.2 theme his Quick checkout

### ISSUE THREAD

**Issue by lamz3** [mijora/omniva-opencart#21]
Hi! The most interesting thing is that this does not work only with Mozilla, with Chrome everything is ok

![image](https://github.com/mijora/omniva-opencart/assets/146752049/0a045cc7-a3aa-469e-af52-85e0d121bb0e)

p.s of course, all the cache in the browser is cleared, and I tested it under a private tab, it doesn't help, the version of omniva module is the latest at the moment (v2.1.1)

**Comment by markakk** [comment]
If you still need help, please contact Omniva about the problem.
