### ISSUE TITLE
cannot print label directly from opencart platform

### ISSUE THREAD

**Issue by Digileksik1** [mijora/omniva-opencart#3]
Sveiki,
modulis atrodo veikia tinkamai, pavyksta atnaujinti terminalus, omnivos internetinėje platformoje taip pat pavyksta užregistruoti lipdukus, tačiau kai opencart platformoje bandome atspausdinti lipduką gauname klaidą label was not received. Galbūt galite nukreipti reikiama linkme, kur ieškoti problemos? Administratoriaus teisės suteiktos, manifestą spausdinti ir užregistruoti siuntas sistema leidžia. Galbūt kažkur nėra kokio nors leidimo ?

**Comment by LithMage** [comment]
Sveiki,

įsitikinkit jog teisingai sukonfigūravote API raktą ir slaptažodį - turėkite omeny jog tai nėra tas pats kas jungiantis prie savitarnos. API raktą ir slaptažodį suteikia Omniva vadybininkas

**Comment by Digileksik1** [comment]
Varototjų grupėje administratoriaus aplinkoje duoti leidimai prieigos ir redagavimo teisėms Omniva_m moduliui. ( extension/module/omniva_m).
Pačio modulio nustatymo lange kur API suvesta viskas pagal instrukcijas. Omnivos serveris ten įvestas automatiškai.
Slaptažodis ir vartotojo vardas įvesti tie kuriuos suteikė omniva vadybininkas. (žinome, kad skiriasi , kreipėmės ir į juos gal pas juos bėda). Be to jei būtų blogi duomenys tikriausiai neleistų užregistruoti naujos siuntos, nes suteikia ir sekimo kodą ir leidžia spausdinti manifestą ir atnaujinti terminalus. Negalime tik spausdinti lipduko.
Galbūt reikia pačiame domene kažką pakeisti ? PHP leidimo gal kokio reikia? O gal ftp kokiam katalogui trūksta 775 ar 777?
Ir nematome jokio klaidos kodo. 
![Untitled3](https://user-images.githubusercontent.com/116888392/204636443-12a92621-6eec-42df-8cc8-e484762c9ad0.jpg)

**Comment by LithMage** [comment]
Sveiki. Gan keista situacija. Prašome susisiekite su mumis ***@***.***
nurodydami svetaine ir jei galite admin prieiga ir kokį užsakymą
pasimėginti spausdinti lipduką.

**Comment by Digileksik1** [comment]
Sveiki,
į kokį elektroninį paštą atsiųsti privačius duomenis?

2022-11-29, an, 23:57 Rimvydas ***@***.***> rašė:

> Sveiki. Gan keista situacija. Prašome susisiekite su mumis ***@***.***
> nurodydami svetaine ir jei galite admin prieiga ir kokį užsakymą
> pasimėginti spausdinti lipduką.
>

**Comment by LithMage** [comment]
Rasykite į support@mijora.lt
