### ISSUE TITLE
Journal3: leidžia užbaigti užsakymą nepasirinkus paštomato + paštomatai rodomi be dropdown

### ISSUE THREAD

**Issue by rectifierguy** [mijora/omniva-opencart#4]
Sveiki, OpenCart 3.0.3.8 versija:

Esu pasirinkes one page checkout, ką Journal3 tema duoda, tačiau problemos 2 išlenda:

1. Vietoje Dropdown + žemėlapio paštomatų rodo tiesiog visus kelis šimtus paštomatų vienu metu vienas po kito kaip radio pasirinkimą.
2. Leidžia užbaigti užsakymą jeigu nei vienas paštomatas nepasirinktas, turbūt patį pasirinkimą Omniva pasirinkimą traktuoja kaip tinkamą.

Jeigu pasirenku Opencart kelių žingsnių checkout, tai problema kita yra, kad kai užsikrauna shippin skirtukas matosi jog visi tie paštomatai irgi kaip su Journal checkout yra, bet tiesiog greit susiskleidžia ir pasidaro taip kaip turi but: Dropdown tampa.

Gal yra galimybė bent jau kažkurį variantą išspręst?

**Comment by LithMage** [comment]
Sveiki
Journal temai reikalingas pritaikymas, by default one page
checkoutu nepalaikome kol kas.
Nelabai supratau dėl pasirinkimo leidimo - kiekvienas paštomatas yra
legalus pasirinkimas.

Su standartiniu checkout - sąrašas yra laikinai matomas iki užsikrauna
pilnai javascript kodas, tai leidžia turėti atsarginį variantą jei dėl
kažkokių priežasčių modulio js nebūtų užkrautas, nes kaip minėjau anksčiau
kiekvienas iš paštomatų radio yra legalus shipping metodas opencart
atžvilgiu.

Jei norite galite įtraukti šias css taisykles
div.radio:has(input[value^="omniva_m\.terminal_"]) {
    display: none;
}

div.radio:has(div.omniva-terminal-container) {
    display: initial;
}

jos iškart paslėps paštomatų pasirinkimus, ir paštomatų selektorius atsiras
kai užsikraus javascript kodas. Tiesa šios taisyklės neveikia
kolkas firefox naršyklėse.

**Comment by LithMage** [comment]
v2.0.6 turi paprastą pritaikymą Journal 3 temai - sukuriamas select tipo pasirinkimas be žemėlapio.
