### ISSUE TITLE
Bug with registering package second time(update from 0.0.6 to 0.0.7 last version on git at 28.02.2023)

### ISSUE THREAD

**Issue by UnknownCommiter** [mijora/omniva-opencart#9]
After updating previous version opencart 2.3 system(0.0.6 in omniva_m_base.ocmod.xml file) to last one 0.0.7
after pressing print label button(to download label file for printing) plugin is registering package second time with another one track code.
At 0.0.6 version problem was not existing, nothing else was changed in system, no error messages in log files.
second track code is in order comments and that is added can see after page refresh.
For now rolled back to 0.0.6 - no problem, so problem only in 0.0.7 version that is now here on git.

**Comment by markakk** [comment]
If you still need help, please contact Omniva about the problem.
